// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"ddd-example/internal/user/app/adapter"
	"ddd-example/internal/user/app/handler"
	"ddd-example/internal/user/app/service"
	"ddd-example/internal/user/infra"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
	"github.com/joyparty/entity"
)

// Injectors from wire.go:

func initApplication(db *sqlx.DB, dbi entity.DB, cache adapter.Cacher) *Application {
	userDBRepository := infra.NewUserDBRepository(dbi)
	sessionTokenService := &service.SessionTokenService{
		Users: userDBRepository,
	}
	authorizeHandler := &handler.AuthorizeHandler{
		Session: sessionTokenService,
	}
	changePasswordHandler := &handler.ChangePasswordHandler{
		User: userDBRepository,
	}
	userService := &service.UserService{
		Users: userDBRepository,
	}
	loginWithEmailHandler := &handler.LoginWithEmailHandler{
		Session: sessionTokenService,
		Users:   userService,
	}
	logoutHandler := &handler.LogoutHandler{
		Session: sessionTokenService,
	}
	registerHandler := &handler.RegisterHandler{
		Session: sessionTokenService,
		Users:   userService,
	}
	oauthTokenService := &service.OauthTokenService{
		Cache: cache,
	}
	registerWithOauthHandler := &handler.RegisterWithOauthHandler{
		DB:         db,
		Session:    sessionTokenService,
		OauthToken: oauthTokenService,
	}
	oauthDBRepository := infra.NewOauthDBRepository(dbi)
	verifyOauthHandler := &handler.VerifyOauthHandler{
		OauthToken: oauthTokenService,
		Session:    sessionTokenService,
		Oauth:      oauthDBRepository,
		Users:      userDBRepository,
	}
	application := &Application{
		UserRepository:    userDBRepository,
		Authorize:         authorizeHandler,
		ChangePassword:    changePasswordHandler,
		LoginWithEmail:    loginWithEmailHandler,
		Logout:            logoutHandler,
		Register:          registerHandler,
		RegisterWithOauth: registerWithOauthHandler,
		VerifyOauth:       verifyOauthHandler,
	}
	return application
}

// wire.go:

var (
	repositoriesSet = wire.NewSet(wire.NewSet(infra.NewUserDBRepository, wire.Bind(new(adapter.UserRepository), new(*infra.UserDBRepository))), wire.NewSet(infra.NewOauthDBRepository, wire.Bind(new(adapter.OauthRepository), new(*infra.OauthDBRepository))),
	)

	serviceSet = wire.NewSet(wire.Struct(new(service.OauthTokenService), "*"), wire.Struct(new(service.SessionTokenService), "*"), wire.Struct(new(service.UserService), "*"))

	applicationProvider = wire.NewSet(
		repositoriesSet,
		serviceSet, wire.Struct(new(handler.AuthorizeHandler), "*"), wire.Struct(new(handler.ChangePasswordHandler), "*"), wire.Struct(new(handler.LoginWithEmailHandler), "*"), wire.Struct(new(handler.LogoutHandler), "*"), wire.Struct(new(handler.RegisterHandler), "*"), wire.Struct(new(handler.RegisterWithOauthHandler), "*"), wire.Struct(new(handler.VerifyOauthHandler), "*"), wire.Struct(new(Application), "*"),
	)
)
